export default [
  'Crie um orçamento mensal e siga-o corretamente.',
  'Poupe uma parte do seu salário regularmente.',
  'Evite dívidas de cartão de crédito, pague o valor total.',
  'Pesquise antes de fazer compras, em busca de melhores preços.',
  'Invista em conhecimento antes de investir dinheiro.',
  'Diversifique seus investimentos para reduzir riscos.',
  'Considere investir em ações de longo prazo.',
  'Tenha um fundo de emergência para imprevistos.',
  'Evite compras por impulso, reflita antes de gastar.',
  'Negocie taxas e tarifas bancárias sempre que possível.',
  'Aprenda sobre juros compostos, eles podem trabalhar a seu favor.',
  'Priorize o pagamento de dívidas com juros altos primeiro.',
  'Esteja atento às oportunidades de investimento, mas cuidado com golpes.',
  'Mantenha registros claros de suas finanças.',
  'Planeje suas metas financeiras a curto e longo prazo.',
  'Avalie se um gasto é um desejo ou uma necessidade antes de comprá-lo.',
  'Acompanhe seus gastos para identificar áreas de melhoria.',
  'Considere investir em sua educação para aumentar sua renda ao longo do tempo.',
  'Automatize pagamentos para evitar atrasos e multas.',
  'Corte gastos desnecessários periodicamente.',
  'Evite empréstimos de curto prazo de alta taxa de juros.',
  'Pesquise e compare antes de adquirir seguros.',
  'Use cupons, promoções e descontos sempre que possível.',
  'Aprenda a cozinhar em casa em vez de comer fora com frequência.',
  'Reavalie suas assinaturas e cancele as que não usa mais.',
  'Mantenha-se atualizado sobre seus investimentos e reequilibre-os periodicamente.',
  'Estabeleça metas de economia e reserve dinheiro para elas.',
  'Priorize a compra de ativos que valorizam, em vez de bens de consumo.',
  'Evite mexer na sua poupança de aposentadoria, se possível.',
  'Aprenda sobre as diferenças entre renda fixa e renda variável.',
  'Ensine seus filhos sobre dinheiro desde cedo.',
  'Faça compras com uma lista para evitar compras impulsivas.',
  'Considere o custo-benefício ao tomar decisões de gastos.',
  'Invista em sua saúde para evitar altos custos médicos no futuro.',
  'Mantenha um registro de todas as dívidas para um melhor planejamento.',
  'Pague suas contas sempre em dia para manter um bom histórico de crédito.',
  'Reveja seus extratos bancários regularmente em busca de erros.',
  'Use apps de gestão financeira para acompanhar seus gastos.',
  'Evite investir em algo que você não entende completamente.',
  'Avalie os prós e contras de comprar a prazo versus à vista.',
];
